//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRF_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class DayProgress
    {
        public int Id { get; set; }
        public Nullable<int> Calorie { get; set; }
        public Nullable<int> MealCount { get; set; }
        public string MealString { get; set; }

		DayProgress()
		{

		}

		public DayProgress(int id, int? calorie = null, int? mealCount = null)
		{
			Id = id;
			Calorie = calorie;
			MealCount = mealCount;
		}

		public void CreateMealString(List<int> mealIDs)
		{
			Console.WriteLine(mealIDs[0].ToString());
			MealString = "";
			for (int i = 0; i < mealIDs.Count; i++)
			{
				MealString = MealString.Insert(MealString.Length, mealIDs[i].ToString());
				MealString = MealString.Insert(MealString.Length, ";");
				Console.WriteLine(MealString);
			}			
		}
	}
}
